allowBuilds:
  core-js: true
minimumReleaseAgeExclude:
  - prettier@3.9.1
  - vite@8.1.2
onlyBuiltDependencies:
  - core-js
  - esbuild

# 允许的 Peer 依赖版本，解决依赖版本冲突警告
peerDependencyRules:
  allowedVersions:
    eslint: "10"
    vite: "8"
